main: me.firewolf8385.flameperms.FlamePerms
name: FlamePerms
version: 1.0
description: Permission Plugin for 1.15.2

author: firewolf8385

api-version: 1.15

commands:
  flameperms:
    usage: /<command>
    description: Main plugin command
    aliases: [fp, flame, permissions, perms]