#  ______ _                      _____
# |  ____| |                    |  __ \
# | |__  | | __ _ _ __ ___   ___| |__) |__ _ __ _ __ ___  ___
# |  __| | |/ _` | '_ ` _ \ / _ \  ___/ _ \ '__| '_ ` _ \/ __|
# | |    | | (_| | | | | | |  __/ |  |  __/ |  | | | | | \__ \
# |_|    |_|\__,_|_| |_| |_|\___|_|   \___|_|  |_| |_| |_|___/
#
# Version 1.0

# This is used when an update modifies the config. If checks this value and
# warns you when the config file does not match the version needed. This number
# may be changed when the correct additions to the config are made.
configVersion: 1

# -----------------------------------------
#               MySQL
# -----------------------------------------
MySQL:
  host: "localhost"
  port: 3306
  database: "database"
  username: "username"
  password: "password"
  useSSL: true

# -----------------------------------------
#                 Theme
# -----------------------------------------

# Theme modifies the colors for all text
# used by the plugin that cannot be modified
# under Messages.
Theme:

  # Default: "&8"
  color1: "&8"

  # Default: "&6"
  color2: "&6"

  # Default: "&e"
  color3: "&e"

  # Default: "&f"
  color4: "&f"

# -----------------------------------------
#               Settings
# -----------------------------------------


# -----------------------------------------
#               Messages
# -----------------------------------------

# Placeholders:
#  - %group%
#  - %permission%
#  - %target%
#  - %order%
Messages:
  # Usage
  addPermUsage: "&6&lUsage &8- &c/simple addperm [group] [perm]"
  createGroupUsage: "&6&lUsage &8- &c/simple creategroup [group]"
  deleteGroupUsage: "&6&lUsage &80 &c/simple deletegroup [group]"
  removePermUsage: "&6&lUsage &8- &c/simple removeperm [group] [perm]"
  setUsage: "&6&lUsage &8- &c/simple set [player] [group]"
  setFamilyUsage: "&2&lUsage &8- &c/simple setfamily [rank] [family]"
  setOrderUsage: "&2&lUsage &8- &c/simple setorder [rank] [order]"

  # Access
  noPermission: "&6&lError &8- &cYou do not have access to that command."
  mustBePlayer: "&6&lError &8- &cYou must be a player to use that command."

  # Group
  groupAlreadyExists: "&6&lError &8- &cGroup &f%group% &calready exists."
  groupCreated: "&6&lPermissions &8- &aCreated group &f%group%&a."
  groupDeleted: "&6&lPermissions &8- &aCreated group &f%group%&a."
  groupDoesNotExist: "&6&lError &8- &cGroup &f%group% &cdoes not exist."
  setGroup: "&6&lPermissions &8- &aSet &f%target%&a's group to &f%group%&a."
  setFamily: "&6&lPermissions &8- &aSet &f%group&&a's family to &f%family%&a."
  setOrder: "&6&lPermissions &8- &aSet &f%group%&a's order to &f%order%&a."

  # Permission
  permissionAdded: "&6&lPermissions &8- &aAdded &f%permission% &ato &f%group%&a."
  permissionRemoved: "&6&lPermissions &8- &aRemove &f%permission% &afrom &f%group%&a."
