#   _____ _                 _      _____                    _         _
#  / ____(_)               | |    |  __ \                  (_)       (_)
# | (___  _ _ __ ___  _ __ | | ___| |__) |__ _ __ _ __ ___  _ ___ ___ _  ___  _ __  ___
#  \___ \| | '_ ` _ \| '_ \| |/ _ \  ___/ _ \ '__| '_ ` _ \| / __/ __| |/ _ \| '_ \/ __|
#  ____) | | | | | | | |_) | |  __/ |  |  __/ |  | | | | | | \__ \__ \ | (_) | | | \__ \
# |_____/|_|_| |_| |_| .__/|_|\___|_|   \___|_|  |_| |_| |_|_|___/___/_|\___/|_| |_|___/
#                    | |
#                    |_|
#
# Version 1.0

# This is used when an update modifies the config. If checks this value and
#warns you when the config file does not match the version needed. This number
# may be changed when the correct additions to the config are made.
configVersion: 1

# -----------------------------------------
#               MySQL
# -----------------------------------------
MySQL:
  host: "localhost"
  port: 3306
  database: "database"
  username: "username"
  password: "password"
  useSSL: true

# -----------------------------------------
#                 Theme
# -----------------------------------------

# Theme modifies the colors for all text
# used by the plugin that cannot be modified
# under Messages.
Theme:

  # Default:
  color1: ""

  # Default:
  color2: ""

  # Defaukt:
  color3: ""

# -----------------------------------------
#               Settings
# -----------------------------------------


# -----------------------------------------
#               Messages
# -----------------------------------------

# Placeholders:
#  - %group%
#  - %permission%
#  - %target%
Messages:
  noPermission: ""
  groupAlreadyExists: ""
  groupCreated: ""
  groupDoesNotExist: ""